[settings]
disable_backends = ["conda"]
lockfile = true
minimum_release_age = "1mo"
experimental = true

[env]
XDG_CACHE_HOME = "${HOME:-$USERPROFILE}/.cache"
XDG_CONFIG_HOME = "${HOME:-$USERPROFILE}/.config"
XDG_DATA_HOME = "${HOME:-$USERPROFILE}/.local/share"

BUNDLE_USER_CACHE = "$XDG_CACHE_HOME/bundle"
BUNDLE_USER_CONFIG = "$XDG_CONFIG_HOME/bundle/config"
BUNDLE_USER_PLUGIN = "$XDG_DATA_HOME/bundle"
CARGO_HOME = "$XDG_DATA_HOME/cargo"
DUB_HOME = "$XDG_DATA_HOME/dub"
GITLIBS = "$XDG_DATA_HOME/gitlibs"
RUSTUP_HOME = "$XDG_DATA_HOME/rustup"

[tools."aqua:fish-shell/fish-shell"]
version = "latest"
os = [ "linux" ]

[tools.bat]
version = "latest"
os = [ "linux" ]

[tools.delta]
version = "latest"
os = [ "linux", "windows" ]

[tools.deno]
version = "latest"
os = [ "linux" ]

[tools.eza]
version = "latest"
os = [ "linux" ]

[tools.fzf]
version = "latest"
os = [ "linux" ]

[tools.github-cli]
version = "latest"
os = [ "linux" ]

[tools.helix]
version = "latest"
os = [ "linux" ]

[tools.lua-language-server]
version = "latest"
os = [ "linux" ]

[tools.neovim]
version = "latest"
os = [ "linux" ]

[tools.ripgrep]
version = "latest"
os = [ "linux" ]

[tools.starship]
version = "latest"
os = [ "linux" ]

[tools.stylua]
version = "latest"
os = [ "linux" ]

[tools.zellij]
version = "latest"
os = [ "linux" ]

[tools.zoxide]
version = "latest"
os = [ "linux" ]
