[hooks.postinstall]
run = "mise --cd ~/.config run init"

[tasks.init]
dir = "~/.config"
run = "just init"
sources = [".gitmodules"]
outputs = ["emacs/.git", "vim/.git"]

[tools.just]
version = "latest"
os = [ "linux", "windows" ]
